# Analysis of spatio-temporal data, WS 2019/2020

# Tour the table:

please share:

* who you are, where you are from, and what kind of BSc program you did
* your prior experience with data analysis: what kind of data, what kind of analysis
* your expectations and hopes for this class

# Goals of this course

For the participants to develop

* an idea about which types of spatio-temporal data there are, what kind of questions we can ask to these data, and how these data can be analysed
* hands-on experience with some of these analysis methods
* experience with common difficulties found in real world datasets
* software skills for analysing spatio-temporal data
* skills to make analyses reproducible, and communicate these

# Course schedule: 

The course will this year mostly focus on the book [Spatio-Temporal Statistics with R](https://spacetimewithr.org/), which is freely available (in pdf form) on-line. The labs are also online.

Thursday sessions will devoted to the labs corresponding to the chapters discussed on Monday. I assume that students will have tried out the labs _before_ the Thursday meeting, and bring their results (success or failure!) to class, where we will share screens.

1. Mon Nov 2 Intro session; 
1. Thu Nov 5 preparations: 
    * get R running on your computer, 
	* install the `STRbook` package in R, 
	* clone the [STRbook_Labs repo](https://github.com/andrewzm/STRbook_Labs), 
	* try to get the first lab (Chap2_Lab1.Rnw) run in R, 
	* if you get stuck, document where you got stuck.
1. Mon Nov 9 Ch 1, 2.1 - 2.3
1. Mon Nov 16 Ch 2.4
1. Mon Nov 23 Ch 3.1 - 3.2 + first assignment
1. Mon Nov 30 Ch 3.3 - 3.5
1. Mon Dec 7 Ch 4.3 - 4.4
1. Mon Dec 14 Ch 5.1 - 5.2
1. Mon Dec 21 Ch 5.3 - 5.5 + winter assignment
1. Mon Jan 11 Ch 6.1 - 6.3
1. Mon Jan 18 Spatial point patterns and movement data
1. Mon Jan 25
1. Mon Feb 1
1. Mon Feb 8 Final assignment presentation of preliminary results; (final assignment hand in: last week of March).

# Introduction

1. What are spatiotemporal data? (is it spatio-temporal or spatiotemporal?)
1. What is involved in data analysis?
1. How do we analyse data?
1. What is data science? Is geoinformatics a data science?
1. What is [R](https://www.r-project.org/)? 
1. Why do we use 
    - R?
    - [R-markdown](http://rmarkdown.rstudio.com/)?
	- [rstudio](http://rstudio.com/)?

# 2. Exercise Nov 5:

For those *unfamiliar* with R (note that this is a lot of work!):

1. Start R
1. Open http://www.r-project.org/ in a browser
1. Browse to Documentation: Manuals
1. Open: An Introduction to R (base R)
1. Work your way through chapters 1-9. (base R)
1. Alternative: [ModernDive: getting started with R](https://moderndive.com/1-getting-started.html) (tidyverse)
1. Alternative: [R for data science](http://r4ds.had.co.nz/) (tidyverse)

For the following data:

```{r}
x = c(1,2,4,5)
y = c(2,1,5,4)
data.frame(x,y)
plot(x,y)
```

## Review/refresher questions:

1. How is the mean for a random variable $X$ defined?
1. Give the equation for covariance between two variables $x$ and $y$
1. Give the equation for correlation between two variables $x$ and $y$
1. For the samples $x$ and $y$, compute the sample mean, the variance and the standard deviation 
1. Draw the data in a scatter plot (by hand)
1. From the table above, compute the covariance between $x$ and $y$, and the correlation between $x$ and $y$
1. Suppose $x$ is a time series data, and the rows indicating the time index. Compute the lag 0, lag 1 and lag 2 autocorrelations of $x$.
1. What is the general equation of an autoregressive AR(p) process?
1. What is the general equation of a moving average MA(q) process?
1. Up to which lag is an AR(p) process correlated?
1. Up to which lag is a MA(q) process correlated?
1. What can be said about partial correlations of an AR(2) process?
