# assignment; areal/lattice data

## assignment WS 2018/19

The assignment is to carry out a spatio-temporal analysis on a
dataset of your choice, using one of the methods that we dealt with
during the course so far, or another (after approval), and report
on this.

The report shall:

* deal with a problem that is solved by analysing spatiotemporal data
* have 1000-2000 words of free text (i.e., excluding the script)
* be structured like a short scientific report (introduction, data, methods, results, discussion and conclusion, list of references)
* state in the introduction clearly the research question (or hypothesis)
* the reference list shall include at least three pieces of related work
* each of the works listed in the references shall be referred to in the main text
* be written in scientific style
* be kept simple
* the analysis shall be part of the text flow, figures (and/or tables) shall support the discussion and conclusions, and shall not be suppressed on output

The report must be submitted as a single .zip file with 

* the report in an R-Markdown file (or similar), 
* the data used, 
* the final form (either html or pdf)

The report shall be reproducible based on the included .Rmd file and the material in the .zip file.

## Areal / lattice data.

For typical lattice data, observed values are associated with
areas, and the union of the areas observed cover the region of
interest. The boundaries of the areas do not follow from the observed
phenomen's properties, but typically from external constraints to
the observation process.

Examples include:

* socio-economic data, related to administrative regions (census, administration)
* health data, related to hospital wards, or aggregated to adm. regions
* satellite imagery (aggregates, related to pixels)
* climate model predictions, as aggregates over regions

Problems include:

* estimate proportions or risks from count data
* areal interpolation: interpolate (downscale/upscale) the observed values to some other units, that are hierchically related to the current areal units (e.g. landsat/modis, change of administrative regions, integration of health and census data)
* evaluating models (testing hypothesis) expressed as $y = X\beta + e$, where either $y$ and/or $e$ exhibit autocorrelation


Typical analysis (see R package `spdep`) follows a path:

* build, and evaluate a spatial weight matrix (based on neighbours, or distance, or both)
* test for spatial correlation using Moran's I
* give significant spatial correlation, build models that account for that

Models used:
* simultaneous autoregressive models (asdar 2nd ed, 9.4.1.1)
* conditional autoregressive models (asdar 2nd ed, 9.4.1.2)

Useful spdep vignettes:

* [creating neighbours](https://cran.r-project.org/web/packages/spdep/vignettes/nb.pdf)
* [Introduction to the North Carolina SIDS dataset](https://cran.r-project.org/web/packages/spdep/vignettes/sids.pdf)
* [Spatial weights objects as sparse matrices and graphs](https://cran.r-project.org/web/packages/spdep/vignettes/nb_igraph.html)
* ["The Problem of Spatial Autocorrelation:" forty years on](https://cran.r-project.org/web/packages/spdep/vignettes/CO69.pdf)

More modern approaches, using R-INLA:

* [Spatial Data Analysis with R-INLA with Some Extensions](https://www.jstatsoft.org/article/view/v063i20)
