# Inference

* inference is the act of trying to draw conclusions beyond mere observations
* it involves adopting assumptions, either about
    * the _sampling_ process (e.g., data was collected completely at random)
	* the process (e.g., the time series, or spatial process, is second order stationary)
* conclusion from inference can never be _certain_ (think: climate change,
human impact on); this means that they need to be accompanied by probability
statements ("it is very likely that" indicates, in IPCC terms, 90-100% probability;
see e.g. table 1 in: https://www.ipcc.ch/site/assets/uploads/2017/08/AR5_Uncertainty_Guidance_Note.pdf ),
or take the form of hypothesis testing: we _rejected_ the null hypothesis with 99% confidence.

# Movement

Movement is an inherently spatio-temporal phenomenon: position
(of something) moves over time.

The study of movement data has happened in rather different areas, including

* transporation research, logistics
* ecology (animal movement, cells)
* crowd control
* sports
* GI Science
* Computer science
* political science (countries)
* atmospheric chemistry, oil spills, forest fires etc

## Movement data

Movement data may come from direct, or indirect sources.

* direct: GPS, cell phone triangulation, mix (google timeline), payment transactions, public transportation check in/out, ...
   - GPS: typically sampling density is (nearly) regular, and dense (what is dense enough?)
   - others: sparse sampling, large gaps: interpolation?
* indirect: e.g. from video footage or wind fields: object tracking
   - identify objects (overlap, shade)
   - track them through imagery / raster maps (satellite imagery)

* should movement data be stored as a set of time-stamped fixes, or a set of two-point, time-stamped, duration stamped, "steps" as elementary units? See [here](https://github.com/mablab/sftraj-proposal/issues/1) for a discussion between proponents of both.

## Types of movement

* continuous: rigid objects
* split/merge: countries, rivers, depressions, storms, clouds, oil spills
* discontinuous: e.g. the capital of Germany, chancellor of Germany

## Questions related to movement data

* where was (is) person $x$ at time $t$?
* (when) was person $x$ at location $s$?
* did persons $x$ and $y$ meet in time interval $T$? (alibi problem)
* is the [functional representation](https://www.tandfonline.com/doi/full/10.1080/13658816.2016.1151520) $T \rightarrow S$ a useful model? How do we observe, interpolate, describe, summarise etc.
* how can we interpret (segments of) movement? Activity/transportation mode etc.
* how does a crowd behave? what is the critical density of a crowd?
* given a trajectory $q$, what is the home range of animal $Q$? (utilization distribution)
* on which road am I driving? (map matching) $\Rightarrow$ where am I?
* given a set of trajectories, on which roads can one drive, in which way? How are roads connected?
* transport and logistics: when should the bus leave / how do I optimize a transportation system?
* how do I describe the interactions between moving agents
* what is the activity/transportation mode of person $x$ at time $t$? (at home, at work, biking, running, car, bus, ...)
* how can I organize the traffic in my city, optimize my road network / traffic lights etc.?


## Datasets:

* [argo](http://www-argo.ucsd.edu/index.html), _a global array of 3,800 free-drifting profiling floats that measures thetemperature and salinity of the upper 2000 m of the ocean._
* [GeoLife](https://www.microsoft.com/en-us/download/details.aspx?id=52367) _This GPS trajectory dataset was collected in (Microsoft Research Asia) Geolife project by 182 users in a period of over three years (from April 2007 to August 2012). Last published: August 9, 2012._
* [movebank](https://www.movebank.org/), _Movebank is a free, online database of animal tracking data hosted by the Max Planck Institute for Ornithology. We help animal tracking researchers to manage, share, protect, analyze, and archive their data. Movebank is an international project with over 11,000 users, including people from research and conservation groups around the world._
* citybike hires (pick up, drop off): [NY](https://www.citibikenyc.com/system-data), London
* NY taxi drives: pick up, drop off

## Software:

* R: see [CRAN Task View](https://cran.r-project.org/web/views/SpatioTemporal.html)

## UseR 2016 tutorial material on movement data

Found [here](https://edzer.github.io/UseR2016/#movement-data)
